# Generated by Django 4.2.7 on 2026-09-30 05:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('testcases', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='分组描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_groups', to='projects.project', verbose_name='归属项目')),
            ],
            options={
                'verbose_name': '测试用例分组',
                'verbose_name_plural': '测试用例分组',
                'db_table': 'testcase_groups',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='testcases.testcasegroup', verbose_name='用例分组'),
        ),
        migrations.AddConstraint(
            model_name='testcasegroup',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_testcase_group_name_per_project'),
        ),
    ]
