# Generated by Django 4.2.7 on 2026-09-29 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('llm_judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='kbreportperiod',
            name='kb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_periods', to='llm_judge.knowledgebase', verbose_name='知识库'),
        ),
        migrations.AddField(
            model_name='kbmetricvalue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='llm_judge.kbcompany', verbose_name='主体'),
        ),
        migrations.AddField(
            model_name='kbmetricvalue',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='llm_judge.kbmetric', verbose_name='指标'),
        ),
        migrations.AddField(
            model_name='kbmetricvalue',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='llm_judge.kbreportperiod', verbose_name='报告期'),
        ),
        migrations.AddField(
            model_name='kbmetricvalue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='kbmetric',
            name='kb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='llm_judge.knowledgebase', verbose_name='知识库'),
        ),
        migrations.AddField(
            model_name='kbcompany',
            name='kb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='llm_judge.knowledgebase', verbose_name='知识库'),
        ),
        migrations.AddField(
            model_name='judgerecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='llm_judge.judgebatch', verbose_name='所属批次'),
        ),
        migrations.AddField(
            model_name='judgerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='judgerecord',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='llm_judge.rubric', verbose_name='评分标准'),
        ),
        migrations.AddField(
            model_name='judgebatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='judgebatch',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='llm_judge.rubric', verbose_name='评分标准'),
        ),
        migrations.AddIndex(
            model_name='rubricrule',
            index=models.Index(fields=['rubric', 'enabled'], name='llm_judge_r_rubric__40789f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubricrule',
            unique_together={('rubric', 'rule_key')},
        ),
        migrations.AddIndex(
            model_name='rubricdimension',
            index=models.Index(fields=['rubric', 'sort_order'], name='llm_judge_r_rubric__a0d503_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubricdimension',
            unique_together={('rubric', 'dim_key')},
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['domain', 'is_active'], name='llm_judge_r_domain_e718ca_idx'),
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['is_default'], name='llm_judge_r_is_defa_aff768_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kbreportperiod',
            unique_together={('kb', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='kbmetricvalue',
            unique_together={('company', 'period', 'metric')},
        ),
        migrations.AlterUniqueTogether(
            name='kbmetric',
            unique_together={('kb', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='kbcompany',
            unique_together={('kb', 'name')},
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['-created_at'], name='llm_judge_r_created_cc83bc_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['gate_zone'], name='llm_judge_r_gate_zo_88b4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['vetoed'], name='llm_judge_r_vetoed_78084b_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['rubric', '-created_at'], name='llm_judge_r_rubric__21511c_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['batch'], name='llm_judge_r_batch_i_312ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['final_score'], name='llm_judge_r_final_s_3df443_idx'),
        ),
        migrations.AddIndex(
            model_name='judgebatch',
            index=models.Index(fields=['-created_at'], name='llm_judge_b_created_31b11a_idx'),
        ),
        migrations.AddIndex(
            model_name='judgebatch',
            index=models.Index(fields=['status'], name='llm_judge_b_status_7708b5_idx'),
        ),
        migrations.AddIndex(
            model_name='judgebatch',
            index=models.Index(fields=['rubric'], name='llm_judge_b_rubric__00c567_idx'),
        ),
    ]
