# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to='ui_test_assets/%Y/%m/%d/', verbose_name='文件')),
                ('mime_type', models.CharField(blank=True, max_length=150, verbose_name='MIME类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA256')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_test_file_assets', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_file_assets', to='ui_automation.uiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI测试文件',
                'verbose_name_plural': 'UI测试文件',
                'db_table': 'ui_test_file_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testcasestep',
            name='file_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_case_steps', to='ui_automation.testfileasset', verbose_name='测试文件'),
        ),
        migrations.AlterField(
            model_name='testcasestep',
            name='action_type',
            field=models.CharField(choices=[('click', '点击'), ('fill', '输入文本'), ('getText', '获取文本'), ('waitFor', '等待元素'), ('hover', '悬停'), ('scroll', '滚动'), ('screenshot', '截图'), ('assert', '断言'), ('wait', '等待'), ('switchTab', '切换标签页'), ('uploadFile', '上传文件')], max_length=20, verbose_name='操作类型'),
        ),
    ]
