# Generated by Django 4.2.7 on 2026-09-29 10:19

from django.db import migrations, models


def copy_legacy_file_assets(apps, schema_editor):
    TestCaseStep = apps.get_model('ui_automation', 'TestCaseStep')
    through = TestCaseStep.file_assets.through
    through.objects.bulk_create([
        through(testcasestep_id=step_id, testfileasset_id=file_asset_id)
        for step_id, file_asset_id in TestCaseStep.objects.exclude(
            file_asset_id=None
        ).values_list('id', 'file_asset_id')
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0003_testfileasset_testcasestep_file_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasestep',
            name='file_assets',
            field=models.ManyToManyField(blank=True, related_name='multi_file_test_case_steps', to='ui_automation.testfileasset', verbose_name='测试文件（多选）'),
        ),
        migrations.RunPython(copy_legacy_file_assets, migrations.RunPython.noop),
    ]
