# Generated by Django 4.2.7 on 2026-09-29 10:21

from django.db import migrations, models


def copy_legacy_file_order(apps, schema_editor):
    TestCaseStep = apps.get_model('ui_automation', 'TestCaseStep')
    for step in TestCaseStep.objects.exclude(file_asset_id=None).iterator():
        step.file_asset_order = [step.file_asset_id]
        step.save(update_fields=['file_asset_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0004_testcasestep_file_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasestep',
            name='file_asset_order',
            field=models.JSONField(blank=True, default=list, verbose_name='测试文件顺序'),
        ),
        migrations.RunPython(copy_legacy_file_order, migrations.RunPython.noop),
    ]
