# Generated by Django 4.2.7 on 2026-09-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0005_testcasestep_file_asset_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestep',
            name='action_type',
            field=models.CharField(choices=[('click', '点击'), ('fill', '输入文本'), ('getText', '获取文本'), ('waitFor', '等待元素'), ('waitForEnabled', '等待元素可用'), ('hover', '悬停'), ('scroll', '滚动'), ('screenshot', '截图'), ('assert', '断言'), ('wait', '等待'), ('switchTab', '切换标签页'), ('uploadFile', '上传文件')], max_length=20, verbose_name='操作类型'),
        ),
    ]
