# Generated by Django 4.2.7 on 2026-09-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0008_localexecutionjob_localexecutionartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='data_driven_enabled',
            field=models.BooleanField(default=False, verbose_name='启用数据驱动'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='data_rows',
            field=models.JSONField(blank=True, default=list, verbose_name='测试数据行'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='执行批次'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='data_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='数据行号'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='data_row',
            field=models.JSONField(blank=True, default=dict, verbose_name='执行数据快照'),
        ),
    ]
