# Generated by Django 4.2.7 on 2026-09-30 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0009_testcase_data_driven_enabled_testcase_data_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localexecutionjob',
            name='suite_execution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_job', to='ui_automation.testexecution', verbose_name='套件执行记录'),
        ),
        migrations.AlterField(
            model_name='localexecutionjob',
            name='execution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_job', to='ui_automation.testcaseexecution', verbose_name='执行记录'),
        ),
        migrations.AddConstraint(
            model_name='localexecutionjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('execution__isnull', False), ('suite_execution__isnull', True)), models.Q(('execution__isnull', True), ('suite_execution__isnull', False)), _connector='OR'), name='local_job_one_execution'),
        ),
    ]
