# Generated by Django 4.2.7 on 2026-09-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0010_local_suite_execution'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='localexecutionjob',
            name='local_job_one_execution',
        ),
        migrations.AddConstraint(
            model_name='localexecutionjob',
            constraint=models.CheckConstraint(check=models.Q(('execution__isnull', True), ('suite_execution__isnull', True), _connector='OR'), name='local_job_at_most_one_execution'),
        ),
    ]
