# Generated by Django 4.2.7 on 2026-09-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0011_allow_local_job_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='分组描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_groups', to='ui_automation.uiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI测试用例分组',
                'verbose_name_plural': 'UI测试用例分组',
                'db_table': 'ui_test_case_groups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='ui_automation.testcasegroup', verbose_name='用例分组'),
        ),
        migrations.AddConstraint(
            model_name='testcasegroup',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_ui_test_case_group_name_per_project'),
        ),
    ]
