# Generated by Django 4.2.7 on 2026-09-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0012_testcasegroup_testcase_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestep',
            name='action_type',
            field=models.CharField(choices=[('click', '点击'), ('fill', '输入文本'), ('getText', '获取文本'), ('waitFor', '等待元素'), ('waitForEnabled', '等待元素可用'), ('hover', '悬停'), ('scroll', '滚动'), ('screenshot', '截图'), ('assert', '断言'), ('wait', '等待'), ('switchTab', '切换标签页'), ('uploadFile', '上传文件'), ('selectOption', '选择下拉选项'), ('check', '勾选'), ('uncheck', '取消勾选'), ('press', '键盘按键')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='testcasestep',
            name='assert_type',
            field=models.CharField(blank=True, choices=[('textContains', '文本包含'), ('textEquals', '文本等于'), ('isVisible', '元素可见'), ('exists', '元素存在'), ('hasAttribute', '属性值'), ('notVisible', '元素不可见'), ('notExists', '元素不存在'), ('valueEquals', '输入框值等于'), ('isChecked', '已选中'), ('notChecked', '未选中'), ('isEnabled', '已启用'), ('isDisabled', '已禁用'), ('countEquals', '元素数量等于'), ('urlEquals', '页面网址等于'), ('urlContains', '页面网址包含')], max_length=20, verbose_name='断言类型'),
        ),
    ]
